Add fasta fai

diff --git a/workflows/reference/Snakefile b/workflows/reference/Snakefile
--- a/workflows/reference/Snakefile
+++ b/workflows/reference/Snakefile
@@ -8,6 +8,7 @@ configfile: "config.yaml"
 # it's where they will be stored ~40G
 REF_DIR            = config["ref_dir"]
 GRCH37_FASTA       = join(REF_DIR, config["reference"]["GRCh37_fasta"]["file"])
+GRCH37_FASTA_FAI   = join(REF_DIR, config["reference"]["GRCh37_fasta_fai"]["file"])
 GENETIC_MAP        = join(REF_DIR, config["reference"]["GENETIC_MAP"]["file"])
 GENETIC_MAP_GRCH37 = join(REF_DIR, config["reference"]["genetic_map_GRCh37"]["file"])
 REF_VCF            = join(REF_DIR, config["reference"]["vcfRef"]["file"])
@@ -26,6 +27,11 @@ GRCH37_FASTA_url       = config["reference"]["GRCh37_fasta"]["url"]
 GRCH37_FASTA_mirror    = config["reference"]["GRCh37_fasta"]["mirror"]
 GRCH37_FASTA_basename  = basename(GRCH37_FASTA_url)
 GRCH37_FASTA_md5       = config["reference"]["GRCh37_fasta"]["md5"]
+
+GRCH37_FASTA_FAI_url       = config["reference"]["GRCh37_fasta_fai"]["url"]
+GRCH37_FASTA_FAI_mirror    = config["reference"]["GRCh37_fasta_fai"]["mirror"]
+GRCH37_FASTA_FAI_basename  = basename(GRCH37_FASTA_FAI_url)
+GRCH37_FASTA_FAI_md5       = config["reference"]["GRCh37_fasta_fai"]["md5"]
 
 GENETIC_MAP_url        = config["reference"]["GENETIC_MAP"]["url"]
 GENETIC_MAP_mirror     = config["reference"]["GENETIC_MAP"]["mirror"]
@@ -74,6 +80,7 @@ if need_phase or need_imputation:
         input:
             GRCh37_fasta = GRCH37_FASTA,
             GRCh37_fasta_dict = expand("{ref}.dict", ref=GRCH37_FASTA),
+            GRCh37_fasta_fai = GRCH37_FASTA_FAI,
             GENETIC_MAP = GENETIC_MAP,
             genetic_map_GRCh37 = expand(GENETIC_MAP_GRCH37, chrom=CHROMOSOMES),
             cmmap = expand(CMMAP, chrom=CHROMOSOMES),
@@ -89,6 +96,7 @@ else:
         input:
             GRCh37_fasta = GRCH37_FASTA,
             GRCh37_fasta_dict = expand("{ref}.dict", ref=GRCH37_FASTA),
+            GRCh37_fasta_fai= GRCH37_FASTA_FAI,
             GENETIC_MAP = GENETIC_MAP,
             genetic_map_GRCh37 = expand(GENETIC_MAP_GRCH37, chrom=CHROMOSOMES),
             cmmap = expand(CMMAP, chrom=CHROMOSOMES),
@@ -100,7 +108,8 @@ else:
 
 rule download_GRCh37_fasta:
     output:
-        GRCh37_fasta = GRCH37_FASTA
+        GRCh37_fasta = GRCH37_FASTA,
+        GRCh37_fasta_fai = GRCH37_FASTA_FAI
     conda:
         "../../envs/download.yaml"
     log:
@@ -118,6 +127,13 @@ rule download_GRCh37_fasta:
             fi
             # gzip exit with "decompression OK, trailing garbage ignored". need to silence
             gzip -d {REF_DIR}/human_g1k_v37.fasta.gz |& tee -a {log}
+            
+            wget {GRCH37_FASTA_FAI_url} -P {REF_DIR} --tries 50 -c |& tee -a {log} || wget {GRCH37_FASTA_FAI_mirror} -P {REF_DIR} --tries 50 -c |& tee -a {log}
+            sum2=$(md5sum {REF_DIR}/{GRCH37_FASTA_FAI_basename} | cut -d " " -f1)
+            if [ $sum2 != {GRCH37_FASTA_FAI_md5} ]; then 
+                echo "md5 sum of GRCH37_FAST_FAI is invalid" |& tee -a {log}
+                exit 1
+            fi           
             exit 0
         """
 
